name: 'Build and push to cachix'
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v12
        with:
          name: welteki
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true
      - name: Check flake
        run: nix flake check -L --accept-flake-config
      - name: Build classic-watchdog 🔧
        run: |
          nix build -L .#classic-watchdog --accept-flake-config
          nix eval --json .#classic-watchdog | jq -r | cachix push welteki
      - name: Build of-watchdog 🔧
        run: |
          nix build -L .#of-watchdog --accept-flake-config
          nix eval --json .#of-watchdog | jq -r | cachix push welteki
      - name: Build base images 🔧
        run: |
          nix build .#classic-watchdog-image --accept-flake-config
          nix build .#of-watchdog-image --accept-flake-config
